name: 'Run Colab Python Py37 Pytorch'
description: 'Run Colab Python Py37 Pytorch'
runs:
  using: "composite"
  steps:
    - name: Set up Python 
      uses: actions/setup-python@v2
      with:
        python-version: '3.7.10'

    - name: Install dependencies
      shell: bash
      run: |
        apt-get update
        apt-get install -y zip
        python -m pip install --upgrade pip
        python -m pip install --upgrade setuptools==58.0.4

    - name: Setup env
      shell: bash
      run: |
        if [ ! -d "/opt/conda/envs/py37-jep" ]
        then
          conda create -n py37-jep -y python==3.7.10 setuptools==58.0.4
        fi
        java -version

      env:
        BIGDL_ROOT: ${{ github.workspace }}
        ANALYTICS_ZOO_ROOT: ${{ github.workspace }}
    
    - name: Run test
      shell: bash
      run: |
        set -x
        export CLASSPATH=.:${JAVA_HOME}/lib:${JAVA_HOME}/jre/lib:${JAVA_HOME}/lib/tools.jar:${JAVA_HOME}/lib/dt.jar
        export PATH=${JAVA_HOME}/bin/:${JAVA_HOME}/jre/bin:${PATH}
        export PATH=/opt/work/apache-maven-3.6.3/bin:$PATH 
        echo $JAVA_HOME
        echo $CLASSPATH
        echo $PATH

      env:
        BIGDL_ROOT: ${{ github.workspace }}
        ANALYTICS_ZOO_ROOT: ${{ github.workspace }}
        FTP_URI: ftp://zoo:1234qwer@10.112.231.51
